/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.40.0.0
 *
 * Project: 'lesson' 
 * Target:  'dbg' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f4xx.h"

/* Keil::Device:Startup@2.6.3 */
#define RTE_DEVICE_STARTUP_STM32F4XX    /* Device Startup for STM32F4 */


#endif /* RTE_COMPONENTS_H */
